// import Layout from "../../components/layout";
// import HomeBox from "../../components/layout/homeBox";
// import FeedbackBox from "../../components/swiper/pogination";
// import ConnectBox from "../../components/layout/connectBox";
// import PartnersBox from "../../components/swiper/scrollbar";

// import AboutMain from "./aboutMain";
// import TeamMembers from "./members";
// import { useTranslation } from "react-i18next";

import Head from 'next/head'
import AboutMain from '../components/aboutComponents/main';
import TeamMembers from '../components/aboutComponents/members';
import FeedbackBox from '../components/homeComponents/feedbacks';
import Layout from '../components/layout';
import ConnectBox from '../components/layout/connectBox';
import HomeBox from '../components/layout/homeBox';
import PartnersBox from '../components/swiper/scrollBar';

function AboutUsPage() {
    // const { t } = useTranslation();
    return (
        <div>
            <Head>
                <title>Mimsoft</title>
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Generated by create next app" />

                <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
                <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
                <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
            </Head>

            <Layout>
                <HomeBox name={'about'} title={'aboutTeam'} page={'about'} />
                <AboutMain />
                <TeamMembers />
                <Partners />
                <FeedbackBox />
                <ConnectBox />
            </Layout>
        </div>
    );
}

export default AboutUsPage;



function Partners() {
    // const { t } = useTranslation();
    return (
        <div className="py-40 md:py-60 lg:py-80 bg-bggray">
            <div className="container">
                <p className="text-xxl mb-20 text-white wolkway">Mijoz va Hamkorlar</p>
                <PartnersBox />
            </div>
        </div>
    )
}