import Head from 'next/head'
import MainAbout from '../components/homeComponents/about'
import HomeMain from '../components/homeComponents/main'
import Services from '../components/homeComponents/services'
import Layout from '../components/layout'
import 'remixicon/fonts/remixicon.css'
import AOS from 'aos';
import 'aos/dist/aos.css';
import React, { useEffect } from 'react'
import PartnersBox from '../components/swiper/scrollBar'
import MainPortfolio from '../components/homeComponents/portfolio'
import FeedbackBox from '../components/homeComponents/feedbacks'
import ConnectBox from '../components/layout/connectBox'
import QuestionBox from '../components/homeComponents/question'

export default function Home() {
  useEffect(() => {
    AOS.init();
  }, [AOS])

  return (
    <div>
      <Head>
        <title>Mimsoft</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />

        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
                <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>

      <Layout>
        <HomeMain />
        <Services />
        <MainPortfolio />
        <MainAbout />
        <MainPartnersBox />
        <FeedbackBox />
        <QuestionBox />
        <ConnectBox />
      </Layout>
    </div>
  )
}

function MainPartnersBox() {
  // const { t } = useTranslation();
  return (
    <div className="py-80 md:py-120 lg:py-160 bg-bggray">
      <div className="container">
        <p className="text-xxl mb-20 text-white wolkway">Mijoz va hamkorlar</p>
        <PartnersBox />
      </div>
    </div>
  )
}
