import Head from 'next/head'
import Layout from "../components/layout";
import ConnectBox from "../components/layout/connectBox";
import HomeBox from "../components/layout/homeBox";
import PortfolioBox from "../components/portfolioComponents/portfolioBox";

function Portfolio() {
    // const { t } = useTranslation();
    return (
        <div>
            <Head>
                <title>Mimsoft</title>
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Generated by create next app" />

                <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
                <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
                <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
            </Head>

            <Layout>
                <HomeBox name={'portfolio'} title={'portfolioSlogan'} page={'portfolio'} />
                <PortfolioBox />
                <ConnectBox />
            </Layout>
        </div>
    );
}

export default Portfolio;